# suppress inspection "UnusedProperty" for whole file


spring.kafka:
  consumer:
    group-id: foo
    auto-offset-reset: earliest
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties.spring.json.trusted.packages: jupiterpa.model
  producer:
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer




logging:
  level:
    root: WARN
    org.springframework.web: INFO
    jupiterpa: INFO
